In [1]:
# Import Dependencies
from pathlib import Path
import pandas as pd

In [3]:
# Create a file path to the owid-covid-data.csv file.
csv_path = Path("owid-covid-data.csv")

# Import the owid-covid-data.csv file as a DataFrame
dataset_df = pd.read_csv(csv_path)

dataset_df.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-01-03,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-01-04,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-01-05,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-01-06,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-01-07,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN

In [7]:
# Remove unnecessary columns from the DataFrame and save the new DataFrame

reduced_df = dataset_df[["location", "date", "total_cases_per_million", "new_cases_smoothed_per_million", "total_deaths_per_million", 
                       "new_deaths_smoothed_per_million", "icu_patients_per_million", 
                       "hosp_patients_per_million", "total_vaccinations_per_hundred", "people_fully_vaccinated_per_hundred",
                      "total_boosters_per_hundred", "new_vaccinations_smoothed_per_million", "new_people_vaccinated_smoothed_per_hundred",
                      "stringency_index", "population_density", "median_age", "extreme_poverty", "cardiovasc_death_rate",
                      "diabetes_prevalence", "female_smokers", "male_smokers", "hospital_beds_per_thousand", "population"]]
reduced_df.head()

,location,date,total_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,new_deaths_smoothed_per_million,icu_patients_per_million,hosp_patients_per_million,total_vaccinations_per_hundred,people_fully_vaccinated_per_hundred,...,stringency_index,population_density,median_age,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,hospital_beds_per_thousand,population
0,Afghanistan,2020-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,54.422,18.6,NaN,597.029,9.59,NaN,NaN,0.5,41128772.0
1,Afghanistan,2020-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,54.422,18.6,NaN,597.029,9.59,NaN,NaN,0.5,41128772.0
2,Afghanistan,2020-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,54.422,18.6,NaN,597.029,9.59,NaN,NaN,0.5,41128772.0
3,Afghanistan,2020-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,54.422,18.6,NaN,597.029,9.59,NaN,NaN,0.5,41128772.0
4,Afghanistan,2020-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,54.422,18.6,NaN,597.029,9.59,NaN,NaN,0.5,41128772.0

In [7]:
# Remove unnecessary columns from the DataFrame and save the new DataFrame

countries = ['Australia', 'India', 'Nepal', 'Vietnam']
filtered_df = reduced_df[reduced_df['Country'].isin(countries_to_keep)]

,location,date,total_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,new_deaths_smoothed_per_million,icu_patients_per_million,hosp_patients_per_million,total_vaccinations_per_hundred,people_fully_vaccinated_per_hundred,...,stringency_index,population_density,median_age,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,hospital_beds_per_thousand,population
0,Afghanistan,2020-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,54.422,18.6,NaN,597.029,9.59,NaN,NaN,0.5,41128772.0
1,Afghanistan,2020-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,54.422,18.6,NaN,597.029,9.59,NaN,NaN,0.5,41128772.0
2,Afghanistan,2020-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,54.422,18.6,NaN,597.029,9.59,NaN,NaN,0.5,41128772.0
3,Afghanistan,2020-01-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,54.422,18.6,NaN,597.029,9.59,NaN,NaN,0.5,41128772.0
4,Afghanistan,2020-01-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,54.422,18.6,NaN,597.029,9.59,NaN,NaN,0.5,41128772.0

In [5]:
# Push the remade DataFrame to a new CSV file
renamed_df.to_csv("Output/books_clean.csv",
                  encoding="utf-8", index=False, header=True)